baseurl = "http://localhost:1313/"
languageCode = "zh-cn"
uglyurls = true
relativeURLs=false
title = "linux学习笔记"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
preserveTaxonomyNames = true
disablePathToLower = true

# Enable Google Analytics by entering your tracking id
# googleAnalytics = "c7442f5794ea2abb71c6ff05dc0b8779"

[params]
	# General information
	author = "曾云龙"
	keywords = "linux,学习笔记,曾云龙"
	description = "Linux是一个操作系统。"
	copyright = "版权所有，转载请注明出处"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/eiuapp/linux-hugo"

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# reward button, comment this to disable it
	reward = true

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
		primary = "red"
		accent  = "teal"

	[params.font]
		text = "Ubuntu"
		code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "eiuapp"
	email   = "273412935@qq.com"


[[menu.main]]
	name   = "前言"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "ubuntu"
	identifier = "ubuntu"
	url    = "/ubuntu/"
	weight = 100

[[menu.main]]
	name   = "ssh"
	identifier = "ssh"
	url    = "/ssh/"
	weight = 200

[[menu.main]]
	name   = "tar"
	identifier = "tar"
	url    = "/tar/"
	weight = 300

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
